from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from Foodcourt import views
from django.urls import path
# from .consumers import NotificationConsumer

urlpatterns = [
    path('admin/', admin.site.urls),
    path('payments/', include('payments.urls')),
    path('', views.home_view, name='home'),
    path('terms/', views.terms_view, name='terms'),
    path('privacy/', views.privacy_view, name='privacy'),
    path('riders/', views.rider_view, name='riders'),
    path('riders/api/banks/', views.rider_banks_api, name='rider_banks_api'),
    path('riders/api/banks/resolve/', views.rider_bank_resolve_api, name='rider_bank_resolve_api'),
    path('riders/register/', views.rider_register_view, name='rider_register'),
    path('riders/verify/', views.rider_verify_view, name='rider_verify'),
    path('riders/verify/resend/', views.rider_resend_verification_code, name='rider_resend_verification_code'),
    path('riders/login/', views.rider_login_view, name='rider_login'),
    path('riders/forgot-password/', views.rider_forgot_password_view, name='rider_forgot_password'),
    path('riders/reset-password/', views.rider_reset_password_view, name='rider_reset_password'),
    path('riders/logout/', views.rider_logout_view, name='rider_logout'),
    path('riders/dashboard/', views.rider_dashboard_view, name='rider_dashboard'),
    path('riders/profile/update/', views.rider_profile_update_view, name='rider_profile_update'),
    path('riders/dashboard/online/', views.rider_toggle_online_view, name='rider_toggle_online'),
    path('riders/dashboard/api/', views.rider_deliveries_api, name='rider_deliveries_api'),
    path('riders/dashboard/accept/<int:delivery_id>/', views.rider_accept_delivery_view, name='rider_accept_delivery'),
    path('riders/dashboard/decline/<int:delivery_id>/', views.rider_decline_delivery_view, name='rider_decline_delivery'),
    path('riders/dashboard/status/<int:delivery_id>/', views.rider_delivery_status_view, name='rider_delivery_status'),
    path('riders/dashboard/delivered/<int:delivery_id>/', views.rider_complete_delivery_view, name='rider_complete_delivery'),
    path('restaurants/', views.restaurants_view, name='restaurants'),
    path('restaurant/<int:pk>/', views.restaurant_detail_view, name='restaurant_detail'),
    path('restaurant/<int:pk>/review/', views.submit_review_view, name='restaurant_review'),
    path('cart/', views.cart_view, name='cart'),
    path('api/addresses/', views.address_api, name='address_api'),
    path('api/profile/avatar/', views.profile_pics_api, name='profile_avatar_api'),
    path('tracking/', views.tracking_view, name='tracking'),
    path('tracking/<str:order_id>/', views.tracking_view, name='tracking_detail'),
    path('api/notifications/', views.notifications_api, name='notifications_api'),
    path('api/notifications/read/', views.notifications_read_api, name='notifications_read'),
    path('api/delivery/<str:order_id>/', views.order_delivery_api, name='order_delivery_api'),
    path('api/orders/<str:order_id>/rate-rider/', views.rate_rider_api, name='rate_rider_api'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('admin-dashboard/', views.admin_dashboard_view, name='admin_dashboard'),
    path('admin-dashboard/restaurants/', views.admin_dashboard_view, {'section': 'restaurants'}, name='admin_restaurants'),
    path('admin-dashboard/orders/', views.admin_dashboard_view, {'section': 'orders'}, name='admin_orders'),
    path('admin-dashboard/riders/', views.admin_dashboard_view, {'section': 'riders'}, name='admin_riders'),
    path('admin-dashboard/users/', views.admin_dashboard_view, {'section': 'users'}, name='admin_users'),
    path('admin-dashboard/payments/', views.admin_dashboard_view, {'section': 'payments'}, name='admin_payments'),
    path('admin-dashboard/riders/<int:pk>/approve/', views.approve_rider_view, name='approve_rider'),
    path('admin-dashboard/riders/<int:pk>/reject/', views.reject_rider_view, name='reject_rider'),
    path('admin-dashboard/users/<int:pk>/block/', views.admin_block_user_view, name='admin_block_user'),
    path('admin-dashboard/users/<int:pk>/unblock/', views.admin_unblock_user_view, name='admin_unblock_user'),
    path('admin-dashboard/users/<int:pk>/resend-verification/', views.admin_resend_verification_view, name='admin_resend_verification'),
    path('admin-dashboard/users/<int:pk>/detail-api/', views.admin_user_detail_api, name='admin_user_detail_api'),
    path('admin-dashboard/users/bulk-action/', views.admin_bulk_user_action_view, name='admin_bulk_user_action'),
    path('admin-dashboard/users/export/', views.admin_export_users_view, name='admin_export_users'),
    path('admin-dashboard/audit-log/', views.admin_audit_log_api, name='admin_audit_log'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('restaurant/register/', views.restaurant_register_view, name='restaurant_register'),
    path('verify/', views.verify_view, name='verify'),
    path('verify/resend/', views.resend_verification_code, name='resend_verification_code'),
    path('forgot-password/', views.forgot_password_view, name='forgot_password'),
    path('reset-password/done/', views.reset_password_done_view, name='reset_password_done'),
    path('reset-password/<uidb64>/<token>/', views.reset_password_view, name='reset_password_confirm'),
    path('order/place/', views.place_order_view, name='place_order'),
    path('api/delivery-fee/', views.delivery_fee_api, name='delivery_fee_api'),
    path('admin-dashboard/delivery-settings/', views.admin_delivery_settings_api, name='admin_delivery_settings_api'),
    path('admin-dashboard/restaurants/<int:pk>/update/', views.admin_restaurant_update_api, name='admin_restaurant_update_api'),
    path('logout/', views.logout_view, name='logout'),
    path('restaurant-admin/', views.restaurant_dashboard_view, name='restaurant_dashboard'),
    path('restaurant-admin/orders/', views.restaurant_dashboard_view, {'section': 'orders'}, name='restaurant_orders'),
    path('restaurant-admin/menu/', views.restaurant_dashboard_view, {'section': 'menu'}, name='restaurant_menu'),
    path('restaurant-admin/categories/', views.restaurant_dashboard_view, {'section': 'categories'}, name='restaurant_categories'),
    path('restaurant-admin/customers/', views.restaurant_dashboard_view, {'section': 'customers'}, name='restaurant_customers'),
    path('restaurant-admin/reviews/', views.restaurant_dashboard_view, {'section': 'reviews'}, name='restaurant_reviews'),
    path('restaurant-admin/inventory/', views.restaurant_dashboard_view, {'section': 'inventory'}, name='restaurant_inventory'),
    path('restaurant-admin/coupons/', views.restaurant_dashboard_view, {'section': 'coupons'}, name='restaurant_coupons'),
    path('restaurant-admin/payments/', views.restaurant_dashboard_view, {'section': 'payments'}, name='restaurant_payments'),
    path('restaurant-admin/settings/', views.restaurant_dashboard_view, {'section': 'settings'}, name='restaurant_settings'),
    path('restaurant-admin/api/', views.restaurant_api_view, name='restaurant_api'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
