# Generated by Django 4.2.27 on 2026-07-31 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodcourt', '0005_category_restaurant_order_is_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='menu_items/'),
        ),
    ]
