# Generated by Django 4.2.27 on 2026-08-03 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Foodcourt', '0008_remove_profile_avatar_profile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Riders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=500, null=True)),
                ('gender', models.CharField(blank=True, max_length=500, null=True)),
                ('is_superuser', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, max_length=500, null=True)),
                ('payments', models.IntegerField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('ph', models.CharField(blank=True, max_length=500, null=True)),
                ('reset', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Riders',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RiderApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=200)),
                ('last_name', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(default='', max_length=500)),
                ('phone', models.CharField(default='', max_length=30)),
                ('dob', models.DateField(blank=True, null=True)),
                ('avatar', models.CharField(blank=True, default='', max_length=500)),
                ('address', models.TextField(default='')),
                ('city', models.CharField(default='', max_length=200)),
                ('state', models.CharField(default='', max_length=200)),
                ('country', models.CharField(default='', max_length=200)),
                ('postal_code', models.CharField(blank=True, default='', max_length=50)),
                ('vehicle_type', models.CharField(default='', max_length=100)),
                ('vehicle_brand', models.CharField(default='', max_length=200)),
                ('vehicle_model', models.CharField(default='', max_length=200)),
                ('vehicle_color', models.CharField(default='', max_length=100)),
                ('vehicle_plate', models.CharField(default='', max_length=100)),
                ('bank_name', models.CharField(default='', max_length=200)),
                ('account_name', models.CharField(default='', max_length=200)),
                ('account_number', models.CharField(default='', max_length=30)),
                ('documents', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rider_application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
