# Generated by Django 4.2.27 on 2026-08-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodcourt', '0009_riders_riderapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
