# Generated by Django 4.2.27 on 2026-08-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodcourt', '0012_riders_standalone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riders',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
