# Generated by Django 4.2.27 on 2026-08-03 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Foodcourt', '0013_alter_riders_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('searching', 'Searching for Rider'), ('assigned', 'Rider Assigned'), ('arrived_at_restaurant', 'Arrived at Restaurant'), ('picked_up', 'Picked Up'), ('on_the_way', 'On The Way'), ('arrived', 'Arrived'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='searching', max_length=30)),
                ('otp', models.CharField(blank=True, default='', max_length=6)),
                ('otp_attempts', models.IntegerField(default=0)),
                ('payout', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at_restaurant_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('on_the_way_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='riders',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='riders',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RiderReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='Foodcourt.delivery')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Foodcourt.riders')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('info', 'Info'), ('order', 'Order'), ('delivery', 'Delivery')], default='info', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True, default='')),
                ('link', models.CharField(blank=True, default='', max_length=300)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Foodcourt.delivery')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Foodcourt.order')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Foodcourt.restaurant')),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Foodcourt.riders')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('label', models.CharField(default='', max_length=100)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='Foodcourt.delivery')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='delivery',
            name='declined_by',
            field=models.ManyToManyField(blank=True, related_name='declined_deliveries', to='Foodcourt.riders'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='notified_riders',
            field=models.ManyToManyField(blank=True, related_name='notified_deliveries', to='Foodcourt.riders'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='Foodcourt.order'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='Foodcourt.riders'),
        ),
    ]
