# Generated by Django 4.2.27 on 2026-08-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodcourt', '0014_delivery_riders_is_available_riders_is_online_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riders',
            name='avatar_image',
            field=models.ImageField(blank=True, null=True, upload_to='rider_pics'),
        ),
    ]
