# Generated by Django 4.2.27 on 2026-08-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodcourt', '0016_add_adminaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_0_2', models.DecimalField(decimal_places=2, default=700, max_digits=8, verbose_name='0–2 km fee')),
                ('tier_2_5', models.DecimalField(decimal_places=2, default=1200, max_digits=8, verbose_name='2–5 km fee')),
                ('tier_5_8', models.DecimalField(decimal_places=2, default=1700, max_digits=8, verbose_name='5–8 km fee')),
                ('tier_8_12', models.DecimalField(decimal_places=2, default=2300, max_digits=8, verbose_name='8–12 km fee')),
                ('tier_12_15', models.DecimalField(decimal_places=2, default=3000, max_digits=8, verbose_name='12–15 km fee')),
                ('max_distance_km', models.DecimalField(decimal_places=1, default=15.0, max_digits=6, verbose_name='Maximum delivery distance (km)')),
                ('surge_enabled', models.BooleanField(default=False, verbose_name='Surge pricing enabled')),
                ('surge_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='Surge multiplier')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Delivery Settings',
                'verbose_name_plural': 'Delivery Settings',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
