# Generated by Django 4.2.27 on 2026-08-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodcourt', '0018_restaurant_area_restaurant_city_restaurant_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='lga',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='location_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='lga',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='location_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
