# Generated by Django 4.2.27 on 2026-08-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodcourt', '0019_address_lga_address_location_confirmed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('category', models.CharField(choices=[('general', 'General Enquiry'), ('order', 'Order Issue'), ('account', 'Account Help'), ('restaurant', 'Restaurant Partnership'), ('rider', 'Rider Application'), ('safety', 'Safety Concern'), ('feedback', 'Feedback'), ('other', 'Other')], default='general', max_length=30)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
