# Generated by Django 4.2.30 on 2026-09-01 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Foodcourt', '0020_contact_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='coupon',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_coupons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coupon',
            name='first_order_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Max discount for percent coupons. 0 = no limit.', max_digits=10),
        ),
        migrations.AddField(
            model_name='coupon',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_uses',
            field=models.IntegerField(default=0, help_text='0 = unlimited'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='restaurant',
            field=models.ForeignKey(blank=True, help_text='Null = platform-wide coupon', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='Foodcourt.restaurant'),
        ),
    ]
